---
- name: Déployer l'API
  hosts: api
  become: true
  vars:
      NODEJS_VERSION: "22"

  tasks:
    - name: Installer les paquets nécessaires (git, curl)
      apt:
        name:
          - git
          - curl
        update_cache: yes

    - name: Ajouter NodeSource et installer Node.js 22.x
      environment:
        DEBIAN_FRONTEND: noninteractive
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
        sudo apt update
        sudo apt install -y nodejs

    - name: Vérifier les versions installées
      shell: |
        node -v
        npm -v

    - name: Cloner le dépôt API
      git:
        repo: 'https://github.com/Projet-CI-CD/API.git'
        dest: /home/lennytooxikx/api
        update: yes

    - name: Donner les droits à l'utilisateur lennytooxikx
      file:
        path: /home/lennytooxikx/api
        owner: lennytooxikx
        group: lennytooxikx
        recurse: yes

    - name: Installer les dépendances Node.js
      become_user: lennytooxikx
      args:
        chdir: /home/lennytooxikx/api
      shell: |
        npm install

    - name: Lancer l'API avec npm start (en arrière-plan)
      become_user: lennytooxikx
      args:
        chdir: /home/lennytooxikx/api
      shell: |
        nohup npm start > app.log 2>&1 &

    - name: Vérifier le log de démarrage
      become_user: lennytooxikx
      shell: tail -n 10 /home/lennytooxikx/api/app.log || echo "Log vide ou inexistant"
