name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v3

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 👤 Set Git user for GitHub App
        run: |
          git config user.name "GitHub App"
          git config user.email "github-app@users.noreply.github.com"

      - name: 📦 Install dependencies
        run: npm install

      - name: 🔧 Give exec permission to release.sh
        run: chmod +x ./release.sh

      - name: 🚀 Run release.sh with standard-version
        env:
          GH_TOKEN: ${{ secrets.APP_TOKEN }}
        run: ./release.sh standard-version

      - name: ✅ Done
        run: echo "Release process completed!"